# Generated by Django 2.0.1 on 2018-01-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_registration_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='paid',
            new_name='paynow',
        ),
    ]
